spring:
  datasource:
    url: jdbc:mysql://localhost:3306/vaccinedb?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: docker@1993#

  jpa:
    show_sql: true
    properties:
      hibernate:
        format_sql: true
        enable_lazy_load_no_trans: true